name: Portmortem
main: someguy.postmortem.Postmortem
version: 1.01
author: Someguyfromcrowd

permissions:
  postmortem.notifyothers:
    description: Send a notification to those with receivenotify upon death
  postmortem.receivenotify:
    description: Receive death notifications