name: Portmortem
main: someguy.postmortem.Postmortem
version: 1.01
author: Someguyfromcrowd

permissions:
  postmortem.notify:
    description: Send a notification to those with receivenotify upon death
  postmortem.receive:
    description: Receive death notifications